server:
  port: 7003



#Eureka配置

eureka:
  instance:
    hostname: eureka7003.com  #Eureka服务器的实例名称
  client:
    register-with-eureka: false #是否向注册中心注册自己
    fetch-registry: false #如果fetch-registry为false 就是注册中心
    service-url: # 监控页面
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/